services:
  - type: web
    name: keystone-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: keystone-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: keystone-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: keystone-db
          property: password
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false

databases:
  - name: keystone-db
    plan: free